id: IF6B4F4B4
legacy_id: P000565
ocr_import_info:
  bdrc_scan_id: W00KG07866
  source: bdrc
  ocr_info:
    timestamp: '2020-03-27T11:17:56'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-29T12:23:30.460347+00:00'
last_modified: 2022-08-29 20:23:42.845026
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W00KG07866
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW00KG07866
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: སྔ་འགྱུར་དགེ་མང་དགོན་གྱི་གདན་རབས་དང་མཁན་དོན་གྲུབ་ཉི་མ་མཆོག་གི་མཛད་རྣམ་མདོར་བསྡུས།
  author: དོན་གྲུབ་ཉི་མ།
statistics:
  ocr_word_mean_confidence_index: 0.7800786829641746
  ocr_word_median_confidence_index: 0.949999988079071
quality: null
bases:
  I00KG010253:
    source_metadata:
      id: http://purl.bdrc.io/resource/I00KG010253
      total_pages: 64
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I00KG010253.txt
    statistics:
      ocr_word_median_confidence_index: 0.949999988079071
      ocr_word_mean_confidence_index: 0.7800786829641746
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
