id: IF6B4F4B4
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T11:18:26+00:00'
last_modified: '2022-06-16T04:58:58.533517+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W00KG07866
  title: སྔ་འགྱུར་དགེ་མང་དགོན་གྱི་གདན་རབས་དང་མཁན་དོན་གྲུབ་ཉི་མ་མཆོག་གི་མཛད་རྣམ་མདོར་བསྡུས
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    78F7:
      image_group_id: I00KG010253
      title: Volume 1 of snga 'gyur dge mang dgon gyi gdan rabs dang mkhan don grub
        nyi ma mchog gi mdzad rnam mdor bsdus
      total_pages: 64
      order: 1
      base_file: 78F7.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
